//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMiLibrero.wsMiLibrero {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alta_Autor_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Alta_Autor_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RESULT {
            get {
                return this.RESULTField;
            }
            set {
                if ((this.RESULTField.Equals(value) != true)) {
                    this.RESULTField = value;
                    this.RaisePropertyChanged("RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta_Autores_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Consulta_Autores_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusField;
        
        private System.DateTime FechaAltaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid IdAutor {
            get {
                return this.IdAutorField;
            }
            set {
                if ((this.IdAutorField.Equals(value) != true)) {
                    this.IdAutorField = value;
                    this.RaisePropertyChanged("IdAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta_Libro_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Consulta_Libro_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdLibroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        private System.Nullable<int> AxoField;
        
        private System.Nullable<int> NoPaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstatusField;
        
        private System.DateTime FechaAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid IdLibro {
            get {
                return this.IdLibroField;
            }
            set {
                if ((this.IdLibroField.Equals(value) != true)) {
                    this.IdLibroField = value;
                    this.RaisePropertyChanged("IdLibro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Axo {
            get {
                return this.AxoField;
            }
            set {
                if ((this.AxoField.Equals(value) != true)) {
                    this.AxoField = value;
                    this.RaisePropertyChanged("Axo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> NoPaginas {
            get {
                return this.NoPaginasField;
            }
            set {
                if ((this.NoPaginasField.Equals(value) != true)) {
                    this.NoPaginasField = value;
                    this.RaisePropertyChanged("NoPaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EstatusField, value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alta_Libro_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Alta_Libro_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RESULT {
            get {
                return this.RESULTField;
            }
            set {
                if ((this.RESULTField.Equals(value) != true)) {
                    this.RESULTField = value;
                    this.RaisePropertyChanged("RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Actualiza_Libro_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Actualiza_Libro_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RESULT {
            get {
                return this.RESULTField;
            }
            set {
                if ((this.RESULTField.Equals(value) != true)) {
                    this.RESULTField = value;
                    this.RaisePropertyChanged("RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Elimina_Libro_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Elimina_Libro_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RESULT {
            get {
                return this.RESULTField;
            }
            set {
                if ((this.RESULTField.Equals(value) != true)) {
                    this.RESULTField = value;
                    this.RaisePropertyChanged("RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsMiLibrero.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Autor", ReplyAction="*")]
        AppMiLibrero.wsMiLibrero.Alta_AutorResponse Alta_Autor(AppMiLibrero.wsMiLibrero.Alta_AutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Autor", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Alta_AutorResponse> Alta_AutorAsync(AppMiLibrero.wsMiLibrero.Alta_AutorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Estatus del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Autores", ReplyAction="*")]
        AppMiLibrero.wsMiLibrero.Consulta_AutoresResponse Consulta_Autores(AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Autores", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Consulta_AutoresResponse> Consulta_AutoresAsync(AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ISBN del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Libro", ReplyAction="*")]
        AppMiLibrero.wsMiLibrero.Consulta_LibroResponse Consulta_Libro(AppMiLibrero.wsMiLibrero.Consulta_LibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta_Libro", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Consulta_LibroResponse> Consulta_LibroAsync(AppMiLibrero.wsMiLibrero.Consulta_LibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ISBN del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Libro", ReplyAction="*")]
        AppMiLibrero.wsMiLibrero.Alta_LibroResponse Alta_Libro(AppMiLibrero.wsMiLibrero.Alta_LibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Alta_Libro", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Alta_LibroResponse> Alta_LibroAsync(AppMiLibrero.wsMiLibrero.Alta_LibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IdLibro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualiza_Libro", ReplyAction="*")]
        AppMiLibrero.wsMiLibrero.Actualiza_LibroResponse Actualiza_Libro(AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualiza_Libro", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Actualiza_LibroResponse> Actualiza_LibroAsync(AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IdLibro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Elimina_Libro", ReplyAction="*")]
        AppMiLibrero.wsMiLibrero.Elimina_LibroResponse Elimina_Libro(AppMiLibrero.wsMiLibrero.Elimina_LibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Elimina_Libro", ReplyAction="*")]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Elimina_LibroResponse> Elimina_LibroAsync(AppMiLibrero.wsMiLibrero.Elimina_LibroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_AutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alta_Autor", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Alta_AutorRequestBody Body;
        
        public Alta_AutorRequest() {
        }
        
        public Alta_AutorRequest(AppMiLibrero.wsMiLibrero.Alta_AutorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Alta_AutorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pais;
        
        public Alta_AutorRequestBody() {
        }
        
        public Alta_AutorRequestBody(string Nombre, string Pais) {
            this.Nombre = Nombre;
            this.Pais = Pais;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_AutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alta_AutorResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Alta_AutorResponseBody Body;
        
        public Alta_AutorResponse() {
        }
        
        public Alta_AutorResponse(AppMiLibrero.wsMiLibrero.Alta_AutorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Alta_AutorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppMiLibrero.wsMiLibrero.Alta_Autor_Result Alta_AutorResult;
        
        public Alta_AutorResponseBody() {
        }
        
        public Alta_AutorResponseBody(AppMiLibrero.wsMiLibrero.Alta_Autor_Result Alta_AutorResult) {
            this.Alta_AutorResult = Alta_AutorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_AutoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_Autores", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Consulta_AutoresRequestBody Body;
        
        public Consulta_AutoresRequest() {
        }
        
        public Consulta_AutoresRequest(AppMiLibrero.wsMiLibrero.Consulta_AutoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta_AutoresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Estatus;
        
        public Consulta_AutoresRequestBody() {
        }
        
        public Consulta_AutoresRequestBody(string Estatus) {
            this.Estatus = Estatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_AutoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_AutoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Consulta_AutoresResponseBody Body;
        
        public Consulta_AutoresResponse() {
        }
        
        public Consulta_AutoresResponse(AppMiLibrero.wsMiLibrero.Consulta_AutoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta_AutoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppMiLibrero.wsMiLibrero.Consulta_Autores_Result[] Consulta_AutoresResult;
        
        public Consulta_AutoresResponseBody() {
        }
        
        public Consulta_AutoresResponseBody(AppMiLibrero.wsMiLibrero.Consulta_Autores_Result[] Consulta_AutoresResult) {
            this.Consulta_AutoresResult = Consulta_AutoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_LibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_Libro", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Consulta_LibroRequestBody Body;
        
        public Consulta_LibroRequest() {
        }
        
        public Consulta_LibroRequest(AppMiLibrero.wsMiLibrero.Consulta_LibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta_LibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ISBN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Autor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Estatus;
        
        public Consulta_LibroRequestBody() {
        }
        
        public Consulta_LibroRequestBody(string ISBN, string Titulo, string Autor, string Estatus) {
            this.ISBN = ISBN;
            this.Titulo = Titulo;
            this.Autor = Autor;
            this.Estatus = Estatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_LibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_LibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Consulta_LibroResponseBody Body;
        
        public Consulta_LibroResponse() {
        }
        
        public Consulta_LibroResponse(AppMiLibrero.wsMiLibrero.Consulta_LibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta_LibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppMiLibrero.wsMiLibrero.Consulta_Libro_Result[] Consulta_LibroResult;
        
        public Consulta_LibroResponseBody() {
        }
        
        public Consulta_LibroResponseBody(AppMiLibrero.wsMiLibrero.Consulta_Libro_Result[] Consulta_LibroResult) {
            this.Consulta_LibroResult = Consulta_LibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_LibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alta_Libro", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Alta_LibroRequestBody Body;
        
        public Alta_LibroRequest() {
        }
        
        public Alta_LibroRequest(AppMiLibrero.wsMiLibrero.Alta_LibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Alta_LibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ISBN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Axo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int NoPaginas;
        
        public Alta_LibroRequestBody() {
        }
        
        public Alta_LibroRequestBody(string ISBN, string Titulo, int Axo, int NoPaginas) {
            this.ISBN = ISBN;
            this.Titulo = Titulo;
            this.Axo = Axo;
            this.NoPaginas = NoPaginas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_LibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Alta_LibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Alta_LibroResponseBody Body;
        
        public Alta_LibroResponse() {
        }
        
        public Alta_LibroResponse(AppMiLibrero.wsMiLibrero.Alta_LibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Alta_LibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppMiLibrero.wsMiLibrero.Alta_Libro_Result Alta_LibroResult;
        
        public Alta_LibroResponseBody() {
        }
        
        public Alta_LibroResponseBody(AppMiLibrero.wsMiLibrero.Alta_Libro_Result Alta_LibroResult) {
            this.Alta_LibroResult = Alta_LibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualiza_LibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualiza_Libro", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Actualiza_LibroRequestBody Body;
        
        public Actualiza_LibroRequest() {
        }
        
        public Actualiza_LibroRequest(AppMiLibrero.wsMiLibrero.Actualiza_LibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Actualiza_LibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdLibro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ISBN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Titulo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Axo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int NoPaginas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string IdAutor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Estatus;
        
        public Actualiza_LibroRequestBody() {
        }
        
        public Actualiza_LibroRequestBody(string IdLibro, string ISBN, string Titulo, int Axo, int NoPaginas, string IdAutor, string Estatus) {
            this.IdLibro = IdLibro;
            this.ISBN = ISBN;
            this.Titulo = Titulo;
            this.Axo = Axo;
            this.NoPaginas = NoPaginas;
            this.IdAutor = IdAutor;
            this.Estatus = Estatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Actualiza_LibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualiza_LibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Actualiza_LibroResponseBody Body;
        
        public Actualiza_LibroResponse() {
        }
        
        public Actualiza_LibroResponse(AppMiLibrero.wsMiLibrero.Actualiza_LibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Actualiza_LibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppMiLibrero.wsMiLibrero.Actualiza_Libro_Result Actualiza_LibroResult;
        
        public Actualiza_LibroResponseBody() {
        }
        
        public Actualiza_LibroResponseBody(AppMiLibrero.wsMiLibrero.Actualiza_Libro_Result Actualiza_LibroResult) {
            this.Actualiza_LibroResult = Actualiza_LibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Elimina_LibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Elimina_Libro", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Elimina_LibroRequestBody Body;
        
        public Elimina_LibroRequest() {
        }
        
        public Elimina_LibroRequest(AppMiLibrero.wsMiLibrero.Elimina_LibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Elimina_LibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IdLibro;
        
        public Elimina_LibroRequestBody() {
        }
        
        public Elimina_LibroRequestBody(string IdLibro) {
            this.IdLibro = IdLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Elimina_LibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Elimina_LibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppMiLibrero.wsMiLibrero.Elimina_LibroResponseBody Body;
        
        public Elimina_LibroResponse() {
        }
        
        public Elimina_LibroResponse(AppMiLibrero.wsMiLibrero.Elimina_LibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Elimina_LibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppMiLibrero.wsMiLibrero.Elimina_Libro_Result Elimina_LibroResult;
        
        public Elimina_LibroResponseBody() {
        }
        
        public Elimina_LibroResponseBody(AppMiLibrero.wsMiLibrero.Elimina_Libro_Result Elimina_LibroResult) {
            this.Elimina_LibroResult = Elimina_LibroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : AppMiLibrero.wsMiLibrero.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<AppMiLibrero.wsMiLibrero.WebService1Soap>, AppMiLibrero.wsMiLibrero.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMiLibrero.wsMiLibrero.Alta_AutorResponse AppMiLibrero.wsMiLibrero.WebService1Soap.Alta_Autor(AppMiLibrero.wsMiLibrero.Alta_AutorRequest request) {
            return base.Channel.Alta_Autor(request);
        }
        
        public AppMiLibrero.wsMiLibrero.Alta_Autor_Result Alta_Autor(string Nombre, string Pais) {
            AppMiLibrero.wsMiLibrero.Alta_AutorRequest inValue = new AppMiLibrero.wsMiLibrero.Alta_AutorRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Alta_AutorRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Pais = Pais;
            AppMiLibrero.wsMiLibrero.Alta_AutorResponse retVal = ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Alta_Autor(inValue);
            return retVal.Body.Alta_AutorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Alta_AutorResponse> AppMiLibrero.wsMiLibrero.WebService1Soap.Alta_AutorAsync(AppMiLibrero.wsMiLibrero.Alta_AutorRequest request) {
            return base.Channel.Alta_AutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Alta_AutorResponse> Alta_AutorAsync(string Nombre, string Pais) {
            AppMiLibrero.wsMiLibrero.Alta_AutorRequest inValue = new AppMiLibrero.wsMiLibrero.Alta_AutorRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Alta_AutorRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Pais = Pais;
            return ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Alta_AutorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMiLibrero.wsMiLibrero.Consulta_AutoresResponse AppMiLibrero.wsMiLibrero.WebService1Soap.Consulta_Autores(AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest request) {
            return base.Channel.Consulta_Autores(request);
        }
        
        public AppMiLibrero.wsMiLibrero.Consulta_Autores_Result[] Consulta_Autores(string Estatus) {
            AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest inValue = new AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Consulta_AutoresRequestBody();
            inValue.Body.Estatus = Estatus;
            AppMiLibrero.wsMiLibrero.Consulta_AutoresResponse retVal = ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Consulta_Autores(inValue);
            return retVal.Body.Consulta_AutoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Consulta_AutoresResponse> AppMiLibrero.wsMiLibrero.WebService1Soap.Consulta_AutoresAsync(AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest request) {
            return base.Channel.Consulta_AutoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Consulta_AutoresResponse> Consulta_AutoresAsync(string Estatus) {
            AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest inValue = new AppMiLibrero.wsMiLibrero.Consulta_AutoresRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Consulta_AutoresRequestBody();
            inValue.Body.Estatus = Estatus;
            return ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Consulta_AutoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMiLibrero.wsMiLibrero.Consulta_LibroResponse AppMiLibrero.wsMiLibrero.WebService1Soap.Consulta_Libro(AppMiLibrero.wsMiLibrero.Consulta_LibroRequest request) {
            return base.Channel.Consulta_Libro(request);
        }
        
        public AppMiLibrero.wsMiLibrero.Consulta_Libro_Result[] Consulta_Libro(string ISBN, string Titulo, string Autor, string Estatus) {
            AppMiLibrero.wsMiLibrero.Consulta_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Consulta_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Consulta_LibroRequestBody();
            inValue.Body.ISBN = ISBN;
            inValue.Body.Titulo = Titulo;
            inValue.Body.Autor = Autor;
            inValue.Body.Estatus = Estatus;
            AppMiLibrero.wsMiLibrero.Consulta_LibroResponse retVal = ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Consulta_Libro(inValue);
            return retVal.Body.Consulta_LibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Consulta_LibroResponse> AppMiLibrero.wsMiLibrero.WebService1Soap.Consulta_LibroAsync(AppMiLibrero.wsMiLibrero.Consulta_LibroRequest request) {
            return base.Channel.Consulta_LibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Consulta_LibroResponse> Consulta_LibroAsync(string ISBN, string Titulo, string Autor, string Estatus) {
            AppMiLibrero.wsMiLibrero.Consulta_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Consulta_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Consulta_LibroRequestBody();
            inValue.Body.ISBN = ISBN;
            inValue.Body.Titulo = Titulo;
            inValue.Body.Autor = Autor;
            inValue.Body.Estatus = Estatus;
            return ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Consulta_LibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMiLibrero.wsMiLibrero.Alta_LibroResponse AppMiLibrero.wsMiLibrero.WebService1Soap.Alta_Libro(AppMiLibrero.wsMiLibrero.Alta_LibroRequest request) {
            return base.Channel.Alta_Libro(request);
        }
        
        public AppMiLibrero.wsMiLibrero.Alta_Libro_Result Alta_Libro(string ISBN, string Titulo, int Axo, int NoPaginas) {
            AppMiLibrero.wsMiLibrero.Alta_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Alta_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Alta_LibroRequestBody();
            inValue.Body.ISBN = ISBN;
            inValue.Body.Titulo = Titulo;
            inValue.Body.Axo = Axo;
            inValue.Body.NoPaginas = NoPaginas;
            AppMiLibrero.wsMiLibrero.Alta_LibroResponse retVal = ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Alta_Libro(inValue);
            return retVal.Body.Alta_LibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Alta_LibroResponse> AppMiLibrero.wsMiLibrero.WebService1Soap.Alta_LibroAsync(AppMiLibrero.wsMiLibrero.Alta_LibroRequest request) {
            return base.Channel.Alta_LibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Alta_LibroResponse> Alta_LibroAsync(string ISBN, string Titulo, int Axo, int NoPaginas) {
            AppMiLibrero.wsMiLibrero.Alta_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Alta_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Alta_LibroRequestBody();
            inValue.Body.ISBN = ISBN;
            inValue.Body.Titulo = Titulo;
            inValue.Body.Axo = Axo;
            inValue.Body.NoPaginas = NoPaginas;
            return ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Alta_LibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMiLibrero.wsMiLibrero.Actualiza_LibroResponse AppMiLibrero.wsMiLibrero.WebService1Soap.Actualiza_Libro(AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest request) {
            return base.Channel.Actualiza_Libro(request);
        }
        
        public AppMiLibrero.wsMiLibrero.Actualiza_Libro_Result Actualiza_Libro(string IdLibro, string ISBN, string Titulo, int Axo, int NoPaginas, string IdAutor, string Estatus) {
            AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Actualiza_LibroRequestBody();
            inValue.Body.IdLibro = IdLibro;
            inValue.Body.ISBN = ISBN;
            inValue.Body.Titulo = Titulo;
            inValue.Body.Axo = Axo;
            inValue.Body.NoPaginas = NoPaginas;
            inValue.Body.IdAutor = IdAutor;
            inValue.Body.Estatus = Estatus;
            AppMiLibrero.wsMiLibrero.Actualiza_LibroResponse retVal = ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Actualiza_Libro(inValue);
            return retVal.Body.Actualiza_LibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Actualiza_LibroResponse> AppMiLibrero.wsMiLibrero.WebService1Soap.Actualiza_LibroAsync(AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest request) {
            return base.Channel.Actualiza_LibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Actualiza_LibroResponse> Actualiza_LibroAsync(string IdLibro, string ISBN, string Titulo, int Axo, int NoPaginas, string IdAutor, string Estatus) {
            AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Actualiza_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Actualiza_LibroRequestBody();
            inValue.Body.IdLibro = IdLibro;
            inValue.Body.ISBN = ISBN;
            inValue.Body.Titulo = Titulo;
            inValue.Body.Axo = Axo;
            inValue.Body.NoPaginas = NoPaginas;
            inValue.Body.IdAutor = IdAutor;
            inValue.Body.Estatus = Estatus;
            return ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Actualiza_LibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMiLibrero.wsMiLibrero.Elimina_LibroResponse AppMiLibrero.wsMiLibrero.WebService1Soap.Elimina_Libro(AppMiLibrero.wsMiLibrero.Elimina_LibroRequest request) {
            return base.Channel.Elimina_Libro(request);
        }
        
        public AppMiLibrero.wsMiLibrero.Elimina_Libro_Result Elimina_Libro(string IdLibro) {
            AppMiLibrero.wsMiLibrero.Elimina_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Elimina_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Elimina_LibroRequestBody();
            inValue.Body.IdLibro = IdLibro;
            AppMiLibrero.wsMiLibrero.Elimina_LibroResponse retVal = ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Elimina_Libro(inValue);
            return retVal.Body.Elimina_LibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Elimina_LibroResponse> AppMiLibrero.wsMiLibrero.WebService1Soap.Elimina_LibroAsync(AppMiLibrero.wsMiLibrero.Elimina_LibroRequest request) {
            return base.Channel.Elimina_LibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMiLibrero.wsMiLibrero.Elimina_LibroResponse> Elimina_LibroAsync(string IdLibro) {
            AppMiLibrero.wsMiLibrero.Elimina_LibroRequest inValue = new AppMiLibrero.wsMiLibrero.Elimina_LibroRequest();
            inValue.Body = new AppMiLibrero.wsMiLibrero.Elimina_LibroRequestBody();
            inValue.Body.IdLibro = IdLibro;
            return ((AppMiLibrero.wsMiLibrero.WebService1Soap)(this)).Elimina_LibroAsync(inValue);
        }
    }
}
